name: Remote Desktop Tunnel

on:
  push:
    branches:
      - main  # تغيير هذا إلى اسم الفرع الرئيسي الخاص بك إذا لزم الأمر
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok
          Remove-Item ngrok.zip  # للقضاء على ملف الضغط

      - name: Set up ngrok
        run: |
          $env:NGROK_AUTH_TOKEN = ${{ secrets.NGROK_AUTH_TOKEN }}
          .\ngrok\ngrok.exe authtoken $env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Remote Desktop
        run: |
          # تمكين الوصول عن بعد لسطح المكتب وتكوين الإعدادات
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Create Tunnel
        run: |
          # بدء نفق ngrok للاتصال بـ RDP (المنفذ 3389)
          Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow

      - name: Wait for ngrok tunnel
        run: |
          # الانتظار لبعض الوقت للسماح لـ ngrok بإنشاء النفق (قم بضبط مدة الانتظار حسب الحاجة)
          Start-Sleep -Seconds 20
        continue-on-error: true

      - name: Get ngrok tunnel URL
        id: get_tunnel_url
        run: |
          # الحصول على عنوان URL للنفق من ngrok
          $ngrokOutput = .\ngrok\ngrok.exe http 4040
          $ngrokTunnelUrl = $ngrokOutput | Select-String -Pattern 'Tunnel Status\:\s+online' -Context 1 | ForEach-Object { $_.Context.PreContext[0] }
          echo "عنوان URL للنفق من ngrok: $ngrokTunnelUrl"
        continue-on-error: true

      - name: Output tunnel URL
        run: |
          # إخراج عنوان URL للنفق كناتج لعملية الخطوة
          echo "::set-output name=tunnel_url::$ngrokTunnelUrl"
        continue-on-error: true

